name: Update Pluto TV M3U

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Bağımlılıkları Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Betiği Çalıştır
      run: python generate_m3u.py

    - name: Değişiklikleri Git'e Commit ve Push Et
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add pluto_tv.m3u
        git status
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update Pluto TV playlist" && git push)
